# Generated by Django 2.2.16 on 2020-09-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produt_status',
            new_name='product_status',
        ),
    ]
