# Generated by Django 2.2.16 on 2020-09-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200922_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_firstname',
            new_name='product_name',
        ),
    ]
